# Generated by Django 4.2.4 on 2023-08-24 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=20)),
                ('year', models.SmallIntegerField()),
                ('gear', models.CharField(choices=[('a', 'automatic'), ('m', 'manual')], max_length=1)),
                ('rent_per_day', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(50)])),
                ('availiability', models.BooleanField(default=True)),
            ],
        ),
    ]
