# Generated by Django 4.2.3 on 2023-07-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('avatar', models.ImageField(blank=True, upload_to='media/', verbose_name='userpicture')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relationsApp.account')),
            ],
            options={
                'verbose_name': 'profile about user',
                'verbose_name_plural': 'users profile',
            },
        ),
    ]
